table gold_employee_aggregated_summary
	lineageTag: ad96887e-258b-4b0a-88e5-3ef00371a4a0

	column cedula
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 5a8ce426-7299-47f8-9075-907ba65b62e8
		summarizeBy: none
		sourceColumn: cedula

		annotation SummarizationSetBy = Automatic

	column multiple_names
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2d83f2ab-fa9f-4d39-958d-a2b634025ae5
		summarizeBy: sum
		sourceColumn: multiple_names

		annotation SummarizationSetBy = Automatic

	column salario
		dataType: double
		sourceProviderType: double
		lineageTag: fa46d31d-62fc-4414-8d8e-500e518046c4
		summarizeBy: sum
		sourceColumn: salario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gasto
		dataType: double
		sourceProviderType: double
		lineageTag: e3c33c32-b670-45ed-b670-91a7a5ff3567
		summarizeBy: sum
		sourceColumn: gasto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column salario_mas_gasto
		dataType: double
		sourceProviderType: double
		lineageTag: b7ea4e00-8039-417c-b7e7-840a06a06e75
		summarizeBy: sum
		sourceColumn: salario_mas_gasto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column conteo_de_cargos
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 27e8217f-a075-4831-bbaa-03b3a8e5f851
		summarizeBy: sum
		sourceColumn: conteo_de_cargos

		annotation SummarizationSetBy = Automatic

	column primera_fecha_inicio
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 03f7e4d4-024a-4a78-bf5c-2fa88d2d2db7
		summarizeBy: none
		sourceColumn: primera_fecha_inicio

		variation Variation
			isDefault
			relationship: f2cbb02c-baed-46ad-8ac7-afdc227f66c8
			defaultHierarchy: LocalDateTable_dbef3d60-5046-482f-b5c3-cbb7ea9274ad.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ultima_fecha_inicio
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 1aa679e0-b381-4510-814a-dc52bff6c4bd
		summarizeBy: none
		sourceColumn: ultima_fecha_inicio

		variation Variation
			isDefault
			relationship: dad0eaf0-8696-4128-a4ba-bf302c222733
			defaultHierarchy: LocalDateTable_208a3b7d-44ac-47bc-bb9d-7f9a21538b77.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column antiguedad
		dataType: double
		sourceProviderType: double
		lineageTag: 3b87eb62-bfb6-4cb5-9278-84d68f9cb485
		summarizeBy: sum
		sourceColumn: antiguedad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column detalle
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 9fdebd36-eebb-4c27-9a44-b766c71fccf2
		summarizeBy: none
		sourceColumn: detalle

		annotation SummarizationSetBy = Automatic

	partition gold_employee_aggregated_summary = m
		mode: import
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs("dbc-f88938f0-02c4.cloud.databricks.com", "/sql/1.0/warehouses/05d15c3c0e634ce9", [Catalog = "", Database = ""]),
				    panama_datos_abiertos_Database = Source{[Name="panama_datos_abiertos",Kind="Database"]}[Data],
				    contraloria_Schema = panama_datos_abiertos_Database{[Name="contraloria",Kind="Schema"]}[Data],
				    resumen_planilla_por_empleados_View = contraloria_Schema{[Name="resumen_planilla_por_empleados",Kind="View"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(resumen_planilla_por_empleados_View,{{"id_number", "cedula"}, {"total_salary", "salario"}, {"total_allowance", "gasto"}, {"total_compensation", "salario_mas_gasto"}, {"distinct_position_count", "conteo_de_cargos"}, {"first_start_date", "primera_fecha_inicio"}, {"last_start_date", "ultima_fecha_inicio"}, {"total_years_of_service", "antiguedad"}, {"positions_details_json", "detalle"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

